### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by jukiginanjar** [ngageoint/projections-ios#10]
I'm not able to build the project after installing `proj-ios` version 2.0.2

#### Version Information:

  * Projections iOS Version: 2.0.2
  * Projections iOS Source: CocoaPods
  * CocoaPods Version: 1.14.3
  * Xcode Version: 15.3
  * Device or Emulator: Emulator
  * iOS Version: 17.4
  * Other Relevant Libraries:

#### Expected Results:

  * Build successfully

#### Observed Results:

  * Build failed

#### Output:
<img width="1733" alt="Screenshot 2024-03-22 at 10 09 15" src="https://github.com/ngageoint/projections-ios/assets/7435655/55d8b735-d26b-46f1-9cd5-68a42f2052f8">
<img width="1479" alt="Screenshot 2024-03-22 at 10 09 36" src="https://github.com/ngageoint/projections-ios/assets/7435655/18ef4d54-c3e7-43a3-ba89-c34b3e5b2bd8">
<img width="1477" alt="Screenshot 2024-03-22 at 10 09 47" src="https://github.com/ngageoint/projections-ios/assets/7435655/5b9c4dc6-a6d7-4742-8169-7a17a2a83c95">

**Comment by bosborn** [comment]
You shouldn't need `use_frameworks!` in your Podfile anymore.  We've dropped it from both our Objective-C and Swift applications.  CocoaPods [added static library support](https://blog.cocoapods.org/CocoaPods-1.5.0/).  You might need to replace it with `use_modular_headers!`. Can you do that?

**Comment by alexbejann** [comment]
@jukiginanjar I had the same problem and opened a [discussion](https://github.com/ngageoint/projections-ios/discussions/7#discussion-6285815) about it. I just added the answer in it
