### ISSUE TITLE
build fail:PROJCRSParser.h:9:9: fatal error: 'proj_api.h' file not found

### ISSUE THREAD

**Issue by kingnight** [ngageoint/projections-ios#5]
#### Version Information:

  * Projections iOS Version: 1.0.5
  * Projections iOS Source: CocoaPods
  * CocoaPods Version:1.11.3
  * Xcode Version:14.2.0
  * Device or Emulator: 
  * iOS Version:
  * Other Relevant Libraries:

brew install automake
brew install libtool
pod repo update
pod install

xcodebuild -workspace 'proj-ios.xcworkspace' -scheme proj-ios build

proj-ios/PROJCRSParser.h:9:9: fatal error: 'proj_api.h' file not found
#import "proj_api.h"
        ^~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

**Comment by bosborn** [comment]
That's not something I can reproduce (on Cocoapods 1.12.1, Xcode 14.3.1).  Are you running this all from the base `projections-ios` cloned directory?  What is the output of the "pod install" command?  Should be something like:

```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing crs-ios (1.0.4)
Installing proj4-ios (4.9.3.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `proj-ios.xcworkspace` for this project from now on.
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.

```

After install, does the file exist at `Pods/proj4-ios/src/proj_api.h`?

Are you able to open (`open proj-ios.xcworkspace`) and build and/or run the tests in Xcode?

Anything else relevant in the xcodebuild output before that error?
